### PR TITLE
MPS 2020.3: Update JBR to 11_0_10-b1341.41

### PR DESCRIPTION
**Pull request by nkoester**

### CODE REVIEW

**Comment by arimer** [comment]
Where did you get this JDK version for the corresponding MPS 2020.3.x version? 
When I check the latest MPS 2020.3.5 release from jetbrains I can see the following version instead:

image

**Comment by nkoester** [comment]
You are correct - I copied the wrong version number from my gradle script - sorry for the confusion.

**Comment by arimer** [comment]
So then the PR is obsolete I guess, because the JBR version for MPS 2020.3.5 is already up to date.

**Comment by nkoester** [comment]
True. Additionally bintray does not serve these files anymore.

**Pull request closed without merging**
